Awesome books es6
karam084/awesome-book-es6 pull request #1
Opened 2022-02-15 23:04 UTC by karam084

* Project requirements

- Create a new directory and initialize it with git.
- Use npm init -y command to create package.json file.
- Create the entry point for your JavaScript code called index.js
- Create index.css file for your styles.
- Create the main index.html file. Link your index.js and index.css files there.
- Create a directory called modules.
- Re-create your Awesome books app following the rules
- Use ES6 syntax.
- Divide your code into modules. Save each module in a separate file in the modules dir. Import modules in the index.js file. For this exercise - the more modules the better!
- Keep all functionalities of the app without errors.
- Display the current date below the navigation bar. - For this requirement, you should use a library - [Luxon](https://moment.github.io/luxon/#/install)

2022-02-15 23:39 UTC, Hamzaoutdoors requested changes
Hey team, I am **Hamza** your reviewer for this PR 😸 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![image](https://media.giphy.com/media/42AFvimyQTNQW44PNG/giphy.gif)

## To Highlight
✔️ The repo looks professional
✔️ Git/GitHub flow best practices have been followed
✔️ There are no linter errors
✔️ You have a descriptive README

## Required Changes ♻️

- [ ] Pleas add `/node_modules` in .gitignore file

_See the inline comments below for more required changes 😃_  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] Please make sure you add meaningful messages to your commits, `Add modules` is very generic and if you find a bug you won't be able to trace down what commit caused it because all the commit messages are the same. Keep this in mind for your future projects as it is a good practice. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @hamzaoutdoors in your question so I can receive the notification ^_^

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-15 23:39 UTC, Hamzaoutdoors commented on index.js
> +function showBooks() {
- [ ] Kindly use `arrow` syntax for functions for best practice of **JavaScript ES6** 👍🏼

2022-02-15 23:39 UTC, Hamzaoutdoors commented on index.js
> +function AddShow() {
- [ ] Kindly use `arrow` syntax for functions for best practice of **JavaScript ES6** 👍🏼

2022-02-15 23:39 UTC, Hamzaoutdoors commented on index.js
> +function showContact() {
- [ ] Kindly use `arrow` syntax for functions for best practice of **JavaScript ES6** 👍🏼

2022-02-15 23:39 UTC, Hamzaoutdoors commented on index.js
> +function Add() {
- [ ] Kindly use `arrow` syntax for functions for best practice of **JavaScript ES6** 👍🏼

2022-02-15 23:39 UTC, Hamzaoutdoors commented on index.js
> +function Remove() {
- [ ] Kindly use `arrow` syntax for functions for best practice of **JavaScript ES6** 👍🏼

2022-02-15 23:39 UTC, Hamzaoutdoors commented on index.js
> +function displayBooks() {
- [ ] Kindly use `arrow` syntax for functions for best practice of **JavaScript ES6** 👍🏼

2022-02-16 00:53 UTC, micheaol approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hi  @karam084 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 00:59 UTC, merged